---
title: "model_notstated"
format: html
---

```{r}
# load libraries
library(dplyr)
library(readr)
library(ggplot2)
library(forcats)
library(rstanarm)
library(knitr)
library(kableExtra)
```

```{r}
# load the dataset 
file_path <- "../data/analysis_data/clean_nyc_data.csv"
nyc_data <- read.csv(file_path)

```

```{r}
# Convert Deaths to numeric if it's not already
nyc_data$Deaths <- as.numeric(as.character(nyc_data$Deaths))

# Filter for the year 2014 and the specific race
race_name <- "Not Stated/Unknown" 

nyc_data_2014_race <- nyc_data %>%
  filter(Year == 2014, Race.Ethnicity == race_name)

# Identify the top 5 causes of death for the selected race
top_causes_by_race <- nyc_data_2014_race %>%
  group_by(Leading.Cause) %>%
  summarise(Total_Deaths = sum(as.numeric(Deaths), na.rm = TRUE), .groups = 'drop') %>%
  arrange(desc(Total_Deaths)) %>%
  slice_max(Total_Deaths, n = 5)

# Ensure data for regression includes only the top causes
nyc_data_for_regression <- nyc_data_2014_race %>%
  inner_join(top_causes_by_race, by = "Leading.Cause")

```

```{r}
# negative binomial regression
neg_binom_model <- stan_glm(
  Total_Deaths ~ Leading.Cause,
  data = nyc_data_for_regression,
  family = neg_binomial_2(link = "log"),
  seed = 853
)

# Output the model summary
model_summary <- summary(neg_binom_model)

# Display the model summary table
kable(model_summary, caption = paste("Negative Binomial Regression Summary for", race_name)) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```


```{r}
# Leave-One-Out Cross-Validation (LOO) for model comparison
loo_neg_binom_notstated <- loo(neg_binom_model)
loo_poisson_notstated <- loo(poisson_model)
loo_comparison_notstated <- loo_compare(loo_neg_binom_notstated, loo_poisson_notstated)
print(loo_comparison_notstated)
```

```{r}
# Posterior Predictive Checks
# Posterior predictive check for the Negative Binomial model
pp_check_neg_binom_notstated <-
  pp_check(neg_binom_model)  + ggtitle("Negative Binomial Model")
ggsave(
  "../data/analysis_data/Model_Output/pp_check_neg_binom_notstated.png",
  plot = pp_check_neg_binom_notstated,
  width = 10,
  height = 8
)
pp_check_neg_binom_notstated

# Posterior predictive check for the Poisson model
pp_check_poisson_notstated <-
  pp_check(poisson_model)  + ggtitle("Poisson Model")
ggsave(
  "../data/analysis_data/Model_Output/pp_check_poisson_notstated.png",
  plot = pp_check_poisson_notstated,
  width = 10,
  height = 8
)
pp_check_poisson_notstated
```